### ISSUE TITLE
schematic of structure of site, interaction of github, xxx.md files, pelican, etc...

### ISSUE THREAD

**Issue by jcdoran** [colinbrislawn/CamerataMusica#18]

**Comment by colinbrislawn** [comment]
I'm mocking this up. Two panel figure: visual analogy on the left, technical terms on the right. 

Github; tower, office building; host everything, both code and people
Pelican; bird, hatch eggs, deliver babies; generates site, `.md` to `.html`
Travis-CI; balloon lifting Pelican nest??; auto build system, runs Pelican

Art style is ink sketch, nothing elaborate.

**Comment by colinbrislawn** [comment]
| Platform   | Data / Action    | Format / Function    | Link                                                                                                     |
|------------|------------------|----------------------|----------------------------------------------------------------------------------------------------------|
| GitHub     | Site source code | .md                  | [main branch](https://github.com/colinbrislawn/CamerataMusica/tree/main/)                                |
| GitHub     | GitHub action    | Builds static site   | [yml file on main](https://github.com/colinbrislawn/CamerataMusica/blob/main/.github/workflows/main.yml) |
| GitHub     | Static Site      | HTML                 | [gh-pages branch](https://github.com/colinbrislawn/CamerataMusica/tree/gh-pages)                         |
| GitHub     | Live site!       | Website              | https://cameratamusica.com/                                                                              |
| Hover      | registrar        | our domain name      | https://hover.com/                                                                                       |
| CloudFlare | DNS and cache    | analytics and cashe  | https://dash.cloudflare.com/                                                                             |
