### ISSUE TITLE
Do everything Steve currently does

### ISSUE THREAD

**Issue by colinbrislawn** [colinbrislawn/CamerataMusica#33]
We need to fully replicate Steve's web stack. This includes
- [x] Set up email marketing, see #32 
- [ ] Consider hosting options (currently Github pages)
- [x] Set up `@cameratamusica.com` email addresses
- [x] Register `cameratamusica.com` through a DNS

**Comment by colinbrislawn** [comment]
One piece of this is `@cameratamusica.com` email addresses. Currently, these ones are listed in Constant Contact:
- steve@cameratamusica.com
- Others???

If the .com domain is registered with Namecheap, they want $10 per year to send from `@cameratamusica.com` email addresses (which is dumb). Hover want's $20 a year. You can _recieve_ email and forward it to an external email address for free simply by setting up [Email Forwarding](https://www.namecheap.com/support/knowledgebase/article.aspx/308/76/how-can-i-set-up-free-email-forwarding-for-my-domain). 

According to @geoffrey-elliott, google apps will replace this service, and it's free for 501(c)3 organizations. So let's just use that.

**Comment by colinbrislawn** [comment]
## Email Marketing
### Price: $0 - $180 a year

I'm suggesting [Benchmark](http://www.benchmarkemail.com/), which is $123 a year for our size, with additional discounts for non-profits.

[MailChimp](https://mailchimp.com/pricing/all/) Is the goto alternative to Constant Contact and it costs $180 a year.

**Comment by colinbrislawn** [comment]
## Register `cameratamusica.com`
### Price: 15$ a year

I'm suggesting [Hover](https://www.hover.com/)

Bonus: [guides for connecting Github pages](http://brendan-quinn.xyz/post/pointing-hover-domain-to-github-pages/)

**Comment by colinbrislawn** [comment]
## Website building and hosting
## Price: $0 or $216 a year

[SquareSpace](https://squarespace.com) is a well regarded choice, and allows for [Seasons of Events](https://support.squarespace.com/hc/en-us/articles/206543837-Using-the-Events-Page) to be created, just like we need.

Currently, I use [GitHub pages](https://pages.github.com/) for hosting and [Pelican](http://docs.getpelican.com/) for building the site. This works great for me, but it's designed to technical users. SquareSpace is accessible to everyone.

**Comment by colinbrislawn** [comment]
- Randy motions: Do all of these, except Website building (GitHub pages is fine). Talk about Squarespace later on.
- Register domain on hover for 5 years. 
- Chris motions: Build a CM site on Squarespace (or others), and report to the board. Up to $250 to spend.

**Comment by colinbrislawn** [comment]
One full season finished successfully! More on the way.

I'll close this for now. (Building the site with squarespace could be it's own issue.)

**Comment by JudithAnnB** [comment]
Colin
We so appreciate you diligence in promoting Camerata Musica!
Thanks so much
Judith
