### ISSUE TITLE
Review MailChimp with CM Board

### ISSUE THREAD

**Issue by colinbrislawn** [colinbrislawn/CamerataMusica#35]
Review cost of MailChimp.

Review email newsletter signup. It's complicated, so I want them to vet it and approve it before it's live.

Also, set up Facebook integration with MailChimp
![](https://media0.giphy.com/media/qMJKg2dNiN2Ks/200.gif)

**Comment by colinbrislawn** [comment]
About 50 addresses on our list are stale, and need cleaning.

I suggest we [sent personalized reconfirmation emails to these folks](http://kb.mailchimp.com/lists/manage-contacts/how-to-reconfirm-a-list#Send-a-Reconfirmation-Message)  and include a link to signup for our newletter again. Then we remove them from our list.

**Comment by JudithAnnB** [comment]
Hello Colin
This sounds like a good idea
However, if the email is “stale”  which I understand to mean
Is no longer valid

Then how will we reach the person anyway?
Judith

**Comment by colinbrislawn** [comment]
Great question, Judith. I've been leaning more about this email system.

Here is how it works: once an email has 'bounced' with a 'return to sender' from the email provider, that address is marked as 'cleaned' and is never used again. So we don't have to worry about them.

In a separate category, there are folks who get out emails, but simply never open them. Maybe they have new email address, or maybe they just never check their mail. We could chose to quietly drop them from the list, or reach out in person so see if they are still interested. If we recognize the name of a friend, we could ask them if they still want to get this email.

**Comment by colinbrislawn** [comment]
Mailchimp has been working pretty good. Making changes to emails is tedious, but I have not explored their API so I can't complain too much. 🙊 I'll close this for now. 🐒 

If we switch to Squarespace for hosting, we could make use of their [MailChimp integration](https://support.squarespace.com/hc/en-us/articles/205815508-Using-MailChimp-with-Squarespace), which might be pretty sweet. IDK.

**Comment by colinbrislawn** [comment]
Mailchimp now does 'single opt-in' to email signup. This is great, but I want to make sure it still works well and iron out any issues. 

Additionally, several (two?) people asked me to add them manually so I should do this as well.
