### ISSUE TITLE
More Modern Methods

### ISSUE THREAD

**Issue by colinbrislawn** [colinbrislawn/CamerataMusica#40]
I would like to make this site as fast and accessible as possible. This has to start with cloudflare: 

- [x] Use the cloudflare CDN
  - official cloudflare [guide](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) 
  - gist [guide](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) 
  - Looks like `Full (strict)` is [more secure](https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/), but not part of the [typical setup](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/#step3timeforssl).
- [ ] Optimizing images programmatically
   - [ ] Use [this plugin](https://github.com/MinchinWeb/minchin.pelican.plugins.optimize_images)!
- [ ] Use the [Google Search Console](https://search.google.com/search-console?resource_id=http://cameratamusica.com/) to add Enhancements (especially a Logo and Events!)

⚡️ 💨 💯 

Articles:
- https://chrishallahan.com/blog/pass-google-pagespeed-performance-test

The [tide has turned](https://twitter.com/lukestevens/status/963905898895699968) on AMP. [Online publishers](https://technology.condenast.com/story/the-why-and-how-of-google-amp-at-conde-nast) need it, but local non-profits don't.

---

Fisher Price ®️ , my first threat model: 
Assets / threats / mitigation
  - domain cameratamusica.com
    - stolen or redirected to other site
       - [ ] check and improve security of Hover (2FA and locked domain)
  - website and email newsletter
    - modified / ads injected
         - [x] use https
         - [x] set up CI properly (I think?)
         - [ ] use industry standard or self hosted JS
  - trust of our users
     - [x] use https to get green lock icon 🔒 💚

**Comment by colinbrislawn** [comment]
Hello @SnorlaxYum

Sorry to bother you. I noticed that you have a [really elegant static site](https://github.com/SnorlaxYum/snorlaxyum.github.io) that's set up a lot like this one, and I wanted to see if you had any advice about Cloudflare's caching. I would like to use caching, but I also want my changes to go live quickly. Any advice you have on this topic would be really helpful. 👍 

Thanks!
Colin

(If not that's ok too. Sorry to @ you out of nowhere.)

**Comment by jcdoran** [comment]
Hi ColinI think you can take me off this mailing list.  Thanks.Hope things are going well with you.ChrisSent from my iPadOn Apr 28, 2023, at 8:07 AM, Colin Brislawn ***@***.***> wrote:﻿
Closed #40 as completed.
