### ISSUE TITLE
Build show for YA 2019

### ISSUE THREAD

**Issue by colinbrislawn** [colinbrislawn/CamerataMusica#42]
https://cameratamusica.com/young-artists-2019.html

**Comment by chudson416** [comment]
HI Colin,Please remove me from this email stream.  I now live in Florida, and too far to visit Camerata!Hope you are doing well.Thanks,Randy Hudson

-----Original Message-----

**Comment by colinbrislawn** [comment]
Sorry to bother you! I hope all is well in Florida.

I can't remove you from this email thread, but you can remove yourself with
the Unsubscribe link below.

**Comment by jcdoran** [comment]
Colin -

I got this email but it looks like it was meant for someone else. 

Chris
